# Generated by Django 6.0.2 on 2026-02-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصف')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='كود الطالب')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم القيد')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم القومي')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True, verbose_name='محل الميلاد')),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('religion', models.CharField(choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي')], max_length=20, verbose_name='الديانة')),
                ('nationality', models.CharField(default='مصري', max_length=100, verbose_name='الجنسية')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('mother_name', models.CharField(max_length=150, verbose_name='اسم الأم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم التليفون')),
                ('enrollment_status', models.CharField(choices=[('New', 'مستجد'), ('Transferred', 'منقول'), ('Home', 'منازل')], default='New', max_length=20, verbose_name='حالة القيد')),
                ('integration_status', models.BooleanField(default=False, verbose_name='موقف الدمج')),
                ('specialization', models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'مطعم'), ('Kitchen', 'مطبخ'), ('Guidance', 'ارشاد'), ('Internal', 'اشراف داخلي'), ('Computer', 'حاسب الي')], max_length=30, null=True, verbose_name='التخصص')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classroom')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
