# Generated by Django 6.0.3 on 2026-04-05 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
            ],
            options={
                'verbose_name': 'تسجيل كورس لطالب',
                'verbose_name_plural': 'سجل اشتراكات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصف')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة الدراسية')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'يسمح بالأرقام فقط.')], verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'اسماء المدرسون',
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع الزي')),
            ],
            options={
                'verbose_name': 'الزي',
                'verbose_name_plural': 'الزي المدرسي',
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع حالياً')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت التحصيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الدفع')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المحصل')),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.coursegroup', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'عملية تحصيل كورس',
                'verbose_name_plural': '3. سجل تحصيلات الكورسات (الخزينة)',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('book', 'كتاب دراسي'), ('uniform', 'زي مدرسي')], default='book', max_length=10, verbose_name='نوع الصنف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الرصيد الافتتاحي')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade', verbose_name='الصف الدراسي')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject', verbose_name='المادة (للكتب)')),
                ('uniform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.uniform', verbose_name='الزي (للملابس)')),
            ],
            options={
                'verbose_name': 'صنف مخزني (جرد)',
                'verbose_name_plural': 'المخزن (الجرد التفصيلي)',
                'ordering': ['id'],
                'unique_together': {('item_type', 'subject', 'uniform', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='InventoryRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية الموردة')),
                ('restock_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوريد')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات (مثل اسم المورد)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='students.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='صورة الطالب')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القيد')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقماً فقط.', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('student_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='كود الطالب')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True, verbose_name='محل الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10, null=True, verbose_name='النوع')),
                ('religion', models.CharField(blank=True, choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي')], max_length=20, null=True, verbose_name='الديانة')),
                ('nationality', models.CharField(blank=True, default='مصري', max_length=100, null=True, verbose_name='الجنسية')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الأم')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='رقم التليفون')),
                ('father_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='وظيفة الأب')),
                ('enrollment_status', models.CharField(blank=True, choices=[('New', 'مستجد'), ('Transferred', 'منقول'), ('Home', 'عمال'), ('Promoted', 'ناجح ومنقول')], max_length=20, null=True, verbose_name='حالة القيد')),
                ('integration_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='موقف الدمج')),
                ('specialization', models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'مطعم'), ('Kitchen', 'مطبخ'), ('Guidance', 'ارشاد'), ('Internal', 'اشراف داخلي'), ('Computer', 'حاسب الي')], max_length=30, null=True, verbose_name='التخصص')),
                ('previous_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مديونية سابقة مرحلة')),
                ('last_promotion_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='finance.academicyear', verbose_name='السنة الدراسية')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classroom', verbose_name='الفصل')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.grade', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='students.student', verbose_name='الطالب'),
        ),
        migrations.CreateModel(
            name='BookSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي المطلوب')),
                ('pay_now', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع الآن')),
                ('status', models.CharField(choices=[('pending', 'لم يكتمل السداد'), ('paid', 'تم السداد بالكامل'), ('delivered', 'تم التسليم فعلياً')], default='pending', max_length=20, verbose_name='حالة الحركة')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='تم الاستلام من المخزن؟')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.inventoryitem', verbose_name='الصنف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إذن استلام ومبيعات',
                'verbose_name_plural': 'إذونات الاستلام والمبيعات',
            },
        ),
        migrations.CreateModel(
            name='SubjectPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('individual', 'كورس (فردي)'), ('group', 'مجموعة (Group)')], default='group', max_length=20, verbose_name='نوع التدريس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'تعريفة سعر مادة',
                'verbose_name_plural': 'أسعار المجموعات والاشتراكات',
                'unique_together': {('teacher', 'subject', 'grade', 'session_type')},
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.subjectprice', verbose_name='بيانات الكورس والسعر'),
        ),
        migrations.CreateModel(
            name='GradePackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر باقة الكتب الإجمالي')),
                ('uniform_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر باقة الزي الإجمالي')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='السنة الدراسية')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'سعر باقة الصف',
                'verbose_name_plural': 'أسعار باقات الصفوف',
                'unique_together': {('academic_year', 'grade')},
            },
        ),
    ]
