# Generated by Django 6.0.3 on 2026-03-22 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصف')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة الدراسية')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'يسمح بالأرقام فقط.')], verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'المدرسون',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='صورة الطالب')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم القيد')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقماً فقط.', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('student_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='كود الطالب')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True, verbose_name='محل الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10, null=True, verbose_name='النوع')),
                ('religion', models.CharField(blank=True, choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي')], max_length=20, null=True, verbose_name='الديانة')),
                ('nationality', models.CharField(default='مصري', max_length=100, verbose_name='الجنسية')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الأم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون')),
                ('enrollment_status', models.CharField(choices=[('New', 'مستجد'), ('Transferred', 'منقول'), ('Home', 'عمال'), ('Promoted', 'ناجح ومنقول')], default='New', max_length=20, verbose_name='حالة القيد')),
                ('integration_status', models.BooleanField(default=False, verbose_name='موقف الدمج')),
                ('specialization', models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'مطعم'), ('Kitchen', 'مطبخ'), ('Guidance', 'ارشاد'), ('Internal', 'اشراف داخلي'), ('Computer', 'حاسب الي')], max_length=30, null=True, verbose_name='التخصص')),
                ('previous_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مديونية سابقة مرحلة')),
                ('last_promotion_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='finance.academicyear', verbose_name='السنة الدراسية')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.classroom', verbose_name='الفصل')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.grade', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(blank=True, max_length=50, verbose_name='الصف الدراسي')),
                ('session_type', models.CharField(choices=[('individual', 'كورس (فردي)'), ('group', 'مجموعة (Group)')], default='group', max_length=20, verbose_name='نوع التدريس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'تسجيل كورس لطالب',
                'verbose_name_plural': 'سجل اشتراكات الطلاب',
            },
        ),
    ]
