# Generated by Django 6.0.3 on 2026-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وظيفة الأب'),
        ),
    ]
