# Generated by Django 6.0.2 on 2026-03-09 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.classroom', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'يجب أن يتكون الرقم القومي من 14 رقماً فقط.'), django.core.validators.MinLengthValidator(14)], verbose_name='الرقم القومي'),
        ),
    ]
