# Generated by Django 6.0.3 on 2026-03-22 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'تسجيل كورس لطالب', 'verbose_name_plural': '2. سجل اشتراكات الطلاب'},
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='teacher',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الاشتراك'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubjectPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('individual', 'كورس (فردي)'), ('group', 'مجموعة (Group)')], default='group', max_length=20, verbose_name='نوع التدريس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'تعريفة سعر مادة',
                'verbose_name_plural': '1. قائمة أسعار المواد (إعدادات)',
                'unique_together': {('teacher', 'subject', 'grade', 'session_type')},
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.subjectprice', verbose_name='بيانات الكورس والسعر'),
            preserve_default=False,
        ),
    ]
