# Generated by Django 6.0.3 on 2026-03-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradepackageprice',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='السنة الدراسية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradepackageprice',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي'),
        ),
        migrations.AlterUniqueTogether(
            name='gradepackageprice',
            unique_together={('academic_year', 'grade')},
        ),
    ]
