# Generated by Django 6.0.3 on 2026-04-08 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بدء الحصص'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='total_sessions',
            field=models.PositiveIntegerField(default=8, verbose_name='إجمالي عدد الحصص المتفق عليها'),
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحصة')),
                ('attendance_status', models.CharField(choices=[('attended', 'حضر'), ('absent', 'غائب'), ('cancelled', 'ملغاة من المركز')], default='attended', max_length=20, verbose_name='حالة الحضور')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات/تقييم الحصة')),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students.coursegroup')),
            ],
            options={
                'verbose_name': 'حصة طالب',
                'verbose_name_plural': 'تتبع حصص الطلاب',
                'unique_together': {('course_enrollment', 'session_date')},
            },
        ),
    ]
