# Generated by Django 6.0.3 on 2026-04-19 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='يجب إدخال رقم موبايل مصري صحيح مكون من 11 رقم', regex='^01[0-9]{9}$')], verbose_name='رقم الواتساب'),
        ),
    ]
