# Generated by Django 6.0.3 on 2026-03-11 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_classroom_alter_student_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الأم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي')], max_length=20, null=True, verbose_name='الديانة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'يسمح بالأرقام فقط.')], verbose_name='كود الطالب'),
        ),
    ]
