# Generated by Django 5.1.5 on 2026-05-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'فني مضيف'), ('Kitchen', 'فن طاهي'), ('Guidance', 'ارشاد'), ('Internal', 'اشراف داخلي')], max_length=30, null=True, verbose_name='التخصص'),
        ),
    ]
