# Generated by Django 6.0.3 on 2026-03-22 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_coursegroup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع حالياً')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت التحصيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الدفع')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المحصل')),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.coursegroup', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'عملية تحصيل كورس',
                'verbose_name_plural': '3. سجل تحصيلات الكورسات (الخزينة)',
            },
        ),
    ]
