# Generated by Django 6.0.3 on 2026-03-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_date_of_birth_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومي'),
        ),
    ]
