# Generated by Django 5.1.5 on 2026-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('New', 'مستجد'), ('Transferred', 'محول'), ('Retained', 'باق'), ('Promoted', 'ناجح ومنقول')], max_length=20, null=True, verbose_name='حالة القيد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'فني مضيف'), ('Kitchen', 'فن طاهي'), ('Internal', 'اشراف داخلي')], max_length=30, null=True, verbose_name='التخصص'),
        ),
    ]
