# Generated by Django 6.0.3 on 2026-03-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_coursepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: باقة كتب الصف الأول الابتدائي', max_length=150, verbose_name='اسم الصنف (كتاب/باقة)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة (المخزن)')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='students.grade', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'صنف كتب / باقة',
                'verbose_name_plural': '1. مخزن الكتب وتحديد الأسعار',
            },
        ),
        migrations.CreateModel(
            name='BookSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية المنصرفة')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الصرف')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.bookitem', verbose_name='الصنف (الكتاب/الباقة)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'عملية صرف كتب',
                'verbose_name_plural': '2. حركة صرف الكتب للطلاب',
            },
        ),
    ]
