# Generated by Django 6.0.3 on 2026-04-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_externalstudent_coursegroup_external_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='external_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.externalstudent', verbose_name='الطالب الخارجي'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='students.student', verbose_name='الطالب المدرسي'),
        ),
    ]
