# Generated by Django 6.0.3 on 2026-03-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_bookitem_booksale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookitem',
            options={'verbose_name': 'صنف كتب / باقة', 'verbose_name_plural': 'مخزن الكتب وتحديد الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='booksale',
            options={'verbose_name': 'عملية صرف', 'verbose_name_plural': 'مليات صرف الكتب '},
        ),
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'تسجيل كورس لطالب', 'verbose_name_plural': 'سجل اشتراكات الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='subjectprice',
            options={'verbose_name': 'تعريفة سعر مادة', 'verbose_name_plural': ' أسعار المجموعات والاشتراكات'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'اسماء المدرسون'},
        ),
        migrations.AddField(
            model_name='bookitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='students.subject', verbose_name='المادة الدراسية'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='book_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.bookitem', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2, editable=False, max_digits=10, verbose_name='الإجمالي'),
            preserve_default=False,
        ),
    ]
