# Generated by Django 5.1.5 on 2026-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'فني مضيف'), ('Kitchen', 'فن طاهي'), ('Internal', ' مشرف غرف')], max_length=30, null=True, verbose_name='التخصص'),
        ),
    ]
