# Generated by Django 6.0.3 on 2026-03-15 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقماً فقط.', regex='^\\d{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='كود الطالب'),
        ),
    ]
