# Generated by Django 5.1.5 on 2026-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payment_cancellation_reason_payment_cancelled_at_and_more'),
        ('students', '0005_alter_student_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'بنين'), ('Female', 'بنات')], db_index=True, max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='integration_status',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='موقف الدمج'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي')], db_index=True, max_length=20, null=True, verbose_name='الديانة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General', 'شعبة عامة'), ('Restaurant', 'فني مضيف'), ('Kitchen', 'فن طاهي'), ('Internal', ' مشرف غرف')], db_index=True, max_length=30, null=True, verbose_name='التخصص'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'id'], name='students_st_first_n_13e3c2_idx'),
        ),
    ]
