# Generated by Django 6.0.3 on 2026-04-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_coursegroup_external_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalstudent',
            name='national_id',
        ),
    ]
