# Generated by Django 6.0.3 on 2026-03-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_national_id_alter_student_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='previous_debt',
        ),
    ]
