# Generated by Django 6.0.3 on 2026-03-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_bookitem_options_alter_booksale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookitem',
            options={'verbose_name': 'كتاب / صنف مخزني', 'verbose_name_plural': 'مخزن الكتب (الجرد التفصيلي)'},
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='name',
            field=models.CharField(help_text='مثال: كتاب اللغة العربية', max_length=150, verbose_name='اسم الكتاب/الصنف'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة للجرد'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject', verbose_name='المادة الدراسية'),
        ),
    ]
