# Generated by Django 6.0.3 on 2026-03-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_bookitem_options_alter_bookitem_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksale',
            options={'verbose_name': 'إذن استلام كتب', 'verbose_name_plural': 'إذونات استلام الكتب والزي'},
        ),
        migrations.AddField(
            model_name='booksale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='booksale',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='تم التسليم فعلياً؟'),
        ),
        migrations.AddField(
            model_name='booksale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'لم يكتمل السداد'), ('ready', 'جاهز للتسليم (تم السداد)'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='book_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.bookitem', verbose_name='الصنف/الكتاب'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
    ]
