# Generated by Django 6.0.3 on 2026-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_externalstudent_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ المطلوب'),
        ),
    ]
