# Generated by Django 5.1.5 on 2026-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_first_name_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الحركة'),
        ),
    ]
