# Generated by Django 6.0.3 on 2026-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_previous_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مديونية سابقة مرحلة'),
        ),
    ]
