# Generated by Django 6.0.3 on 2026-04-10 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_coursegroup_required_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الخط / المنطقة')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم السائق')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف السائق')),
                ('bus_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم اللوحة')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='سعة الباص (عدد الكراسي)')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('term_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر التيرم')),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر السنوي')),
            ],
            options={
                'verbose_name': 'خط باص',
                'verbose_name_plural': 'خطوط الباصات',
            },
        ),
        migrations.CreateModel(
            name='BusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('monthly', 'شهري'), ('term', 'تيرم (فصل دراسي)'), ('yearly', 'سنوي (عام كامل)'), ('custom', 'مخصص')], default='monthly', max_length=20, verbose_name='نوع الاشتراك')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الاشتراك')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الاشتراك')),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المطلوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة الاشتراك (فعال)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='students.busroute', verbose_name='خط الباص')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_subscriptions', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'اشتراك باص',
                'verbose_name_plural': 'اشتراكات الباص',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحصيل')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.bussubscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'تحصيل باص',
                'verbose_name_plural': 'تحصيلات الباص',
            },
        ),
    ]
