# Generated by Django 5.1.5 on 2026-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_booksale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialprogramrecord',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم السداد؟'),
        ),
    ]
