# Generated by Django 6.0.3 on 2026-03-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_booksale_collected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classroom', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('New', 'مستجد'), ('Transferred', 'منقول'), ('Home', 'عمال'), ('Promoted', 'ناجح ومنقول')], max_length=20, null=True, verbose_name='حالة القيد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='integration_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='موقف الدمج'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='مصري', max_length=100, null=True, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القيد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='كود الطالب'),
        ),
    ]
