# Generated by Django 6.0.3 on 2026-04-10 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_busroute_bussubscription_buspayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='بيان الإيراد')),
                ('revenue_type', models.CharField(choices=[('canteen', 'إيجار كانتين'), ('donation', 'تبرعات'), ('activities', 'رسوم أنشطة / رحلات'), ('papers', 'رسوم استخراج أوراق'), ('other', 'أخرى متنوعة')], default='other', max_length=50, verbose_name='تصنيف الإيراد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المورد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت التحصيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستلم')),
            ],
            options={
                'verbose_name': 'إيراد متنوع',
                'verbose_name_plural': 'الإيرادات المتنوعة',
                'ordering': ['-date'],
            },
        ),
    ]
