# Generated by Django 5.1.5 on 2026-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_remedialprogramrecord_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneousrevenue',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإيراد'),
        ),
    ]
