# Generated by Django 5.1.5 on 2026-06-21 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_studentrefund_options_and_more'),
        ('students', '0009_alter_miscellaneousrevenue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReEnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الفصل')),
                ('reenrollment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إعادة القيد')),
                ('status', models.CharField(choices=[('dismissed', 'مفصول لتخطي الغياب'), ('re_enrolled', 'تم إعادة القيد')], default='dismissed', max_length=20, verbose_name='الحالة')),
                ('fee_paid', models.BooleanField(default=False, verbose_name='تم دفع رسوم الإعادة؟')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollments', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل إعادة قيد',
                'verbose_name_plural': 'سجلات إعادة القيد',
            },
        ),
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cultural', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='النهاية العظمى (ثقافي)')),
                ('max_practical', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='النهاية العظمى (عملي)')),
                ('passing_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='درجة النجاح الكلية')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'توزيع درجات المادة',
                'verbose_name_plural': 'توزيع درجات المواد',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ اليوم')),
                ('term', models.CharField(choices=[('term1', 'الترم الأول'), ('term2', 'الترم الثاني'), ('second_session', 'الدور الثاني (ملاحق)')], default='term1', max_length=20, verbose_name='الترم')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'غياب بعذر')], default='present', max_length=10, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل غياب',
                'verbose_name_plural': 'سجلات الغياب',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('month', 'امتحان شهر'), ('term', 'امتحان نهاية ترم'), ('second_session', 'امتحان دور ثاني')], default='term', max_length=20, verbose_name='نوع الامتحان')),
                ('term', models.CharField(choices=[('term1', 'الترم الأول'), ('term2', 'الترم الثاني'), ('second_session', 'الدور الثاني (ملاحق)')], max_length=20, verbose_name='الترم')),
                ('month', models.CharField(blank=True, choices=[('10', 'أكتوبر'), ('11', 'نوفمبر'), ('12', 'ديسمبر'), ('2', 'فبراير'), ('3', 'مارس'), ('4', 'أبريل')], max_length=10, null=True, verbose_name='الشهر (للامتحانات الشهرية)')),
                ('cultural_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة النظري (ثقافي)')),
                ('practical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة العملي')),
                ('is_absent', models.BooleanField(default=False, verbose_name='غائب في الامتحان؟')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'نتيجة امتحان',
                'verbose_name_plural': 'رصد الدرجات',
                'unique_together': {('student', 'subject', 'academic_year', 'exam_type', 'term', 'month')},
            },
        ),
    ]
