# Generated by Django 6.0.3 on 2026-03-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_classroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع الزي')),
            ],
            options={
                'verbose_name': 'الزي',
                'verbose_name_plural': 'الزي المدرسي',
            },
        ),
        migrations.AddField(
            model_name='bookitem',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.uniform', verbose_name='نوع الزي (للملابس فقط)'),
        ),
    ]
