# Generated by Django 6.0.3 on 2026-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_miscellaneousrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'بنين'), ('Female', 'بنات')], max_length=10, null=True, verbose_name='النوع'),
        ),
    ]
