# Generated by Django 6.0.3 on 2026-03-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_uniform_bookitem_uniform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject', verbose_name='المادة الدراسية'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.uniform', verbose_name='الزي المدرسي'),
        ),
    ]
