# Generated by Django 6.0.3 on 2026-04-14 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_monthlyclosure_total_collected_and_more'),
        ('students', '0010_alter_student_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedialFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_per_subject', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='رسوم المادة الواحدة')),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
            ],
        ),
        migrations.CreateModel(
            name='RemedialProgramRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_count', models.PositiveIntegerField(default=1, verbose_name='عدد المواد المتخلف عنها')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الرسوم المطلوبة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم السداد؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسجل البيان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
        ),
    ]
