# Generated by Django 5.1.5 on 2026-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_reenrollmentrecord_subjectconfig_attendancerecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gate_block_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="سبب حظر البوابة"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="is_blocked_at_gate",
            field=models.BooleanField(
                default=False, verbose_name="محظور من الدخول يدوياً"
            ),
        ),
    ]
