# Generated by Django 6.0.3 on 2026-03-24 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_bookitem_subject_alter_bookitem_uniform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksale',
            options={'verbose_name': 'إذن استلام', 'verbose_name_plural': 'إذونات الاستلام'},
        ),
        migrations.AlterModelOptions(
            name='subjectprice',
            options={'verbose_name': 'تعريفة سعر مادة', 'verbose_name_plural': 'أسعار المجموعات والاشتراكات'},
        ),
        migrations.RemoveField(
            model_name='booksale',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='booksale',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='booksale',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='تم الاستلام من المخزن؟'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'لم يكتمل السداد'), ('ready', 'تم السداد (جاهز للاستلام)'), ('delivered', 'تم التسليم فعلياً')], default='pending', max_length=20, verbose_name='حالة السداد'),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة'),
        ),
        migrations.CreateModel(
            name='GradePackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر باقة الكتب الإجمالي')),
                ('uniform_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر باقة الزي الإجمالي')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'سعر باقة الصف',
                'verbose_name_plural': 'أسعار باقات الصفوف',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: كتاب لغة عربية - ترم أول', max_length=150, verbose_name='اسم الصنف التفصيلي')),
                ('item_type', models.CharField(choices=[('book', 'كتاب دراسي'), ('uniform', 'زي مدرسي')], default='book', max_length=10, verbose_name='نوع الصنف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة في المخزن')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject', verbose_name='المادة (للكتب)')),
                ('uniform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.uniform', verbose_name='الزي (للملابس)')),
            ],
            options={
                'verbose_name': 'صنف مخزني (جرد)',
                'verbose_name_plural': 'المخزن (الجرد التفصيلي)',
            },
        ),
        migrations.AlterField(
            model_name='booksale',
            name='book_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.inventoryitem', verbose_name='الصنف المطلوب استلامه'),
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
