# Generated by Django 5.1.5 on 2026-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_student_gate_block_reason_student_is_blocked_at_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gate_blocked_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ بدء الحظر"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gate_blocked_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ نهاية الحظر"
            ),
        ),
    ]
