# Generated by Django 5.1.5 on 2026-07-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_alter_studentrefund_options_and_more"),
        ("students", "0012_student_gate_blocked_from_student_gate_blocked_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectconfig",
            name="max_cultural",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                max_digits=5,
                verbose_name="النهاية العظمى (ثقافي/نظري)",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconfig",
            name="passing_score",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                max_digits=5,
                verbose_name="درجة النجاح الكلية (النهاية الصغرى)",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconfig",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configs",
                to="students.subject",
                verbose_name="المادة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectconfig",
            unique_together={("subject", "grade", "academic_year")},
        ),
        migrations.CreateModel(
            name="StudentControlSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term1_cultural",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ترم أول - نظري",
                    ),
                ),
                (
                    "term1_practical",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ترم أول - عملي",
                    ),
                ),
                (
                    "term1_is_absent",
                    models.BooleanField(
                        default=False, verbose_name="غياب الترم الأول؟"
                    ),
                ),
                (
                    "term2_cultural",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ترم ثاني - نظري",
                    ),
                ),
                (
                    "term2_practical",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ترم ثاني - عملي",
                    ),
                ),
                (
                    "term2_is_absent",
                    models.BooleanField(
                        default=False, verbose_name="غياب الترم الثاني؟"
                    ),
                ),
                (
                    "second_session_cultural",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="دور ثانٍ - نظري",
                    ),
                ),
                (
                    "second_session_practical",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="دور ثانٍ - عملي",
                    ),
                ),
                (
                    "second_session_is_absent",
                    models.BooleanField(
                        default=False, verbose_name="غياب الدور الثاني؟"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "ناجح ومجتاز ✅"),
                            ("second_session", "له دور ثانٍ (ملحق) ⚠️"),
                            ("failed", "راسب وباقٍ للإعادة ❌"),
                        ],
                        default="second_session",
                        max_length=20,
                        verbose_name="الحالة النهائية للمادة",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.academicyear",
                        verbose_name="العام الدراسي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_records",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                        verbose_name="المادة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل الكنترول السنوي",
                "verbose_name_plural": "شيت الكنترول العام (النتائج النهائية)",
                "unique_together": {("student", "subject", "academic_year")},
            },
        ),
    ]
