# Generated by Django 6.0.3 on 2026-03-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_booksale_options_alter_subjectprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['grade', 'subject', 'uniform'], 'verbose_name': 'صنف مخزني (جرد)', 'verbose_name_plural': 'المخزن (الجرد التفصيلي)'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
    ]
