# Generated by Django 5.1.5 on 2026-07-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_alter_studentrefund_options_and_more"),
        ("students", "0013_alter_subjectconfig_max_cultural_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAcademicHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_result",
                    models.CharField(
                        choices=[
                            ("Promoted", "ناجح ومنقول 🎓"),
                            ("Failed", "راسب وباقٍ للإعادة ❌"),
                        ],
                        default="Promoted",
                        max_length=20,
                        verbose_name="النتيجة النهائية للعام",
                    ),
                ),
                (
                    "total_attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        verbose_name="نسبة الحضور الإجمالية %",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="تقرير شئون الطلاب السنوي"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.academicyear",
                        verbose_name="العام الدراسي المخزن",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.classroom",
                        verbose_name="الفصل",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.grade",
                        verbose_name="الصف الدراسي حينها",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_histories",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "أرشيف سنة دراسية لطالب",
                "verbose_name_plural": "سجلات شئون الطلاب التاريخية",
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
