# Generated by Django 6.0.3 on 2026-03-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_inventoryitem_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية الموردة')),
                ('restock_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوريد')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات (مثل اسم المورد)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='students.inventoryitem')),
            ],
        ),
    ]
