# Generated by Django 5.1.5 on 2026-07-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_alter_studentrefund_options_and_more"),
        ("students", "0014_studentacademichistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="study_type",
            field=models.CharField(
                choices=[("Regular", "انتظام"), ("Workers", "عمال")],
                db_index=True,
                default="Regular",
                max_length=20,
                verbose_name="نوع الدراسة",
            ),
        ),
        migrations.CreateModel(
            name="ControlRoomConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "students_per_committee",
                    models.PositiveIntegerField(
                        default=20,
                        verbose_name="سعة اللجنة (عدد الطلاب في الفصل الواحد)",
                    ),
                ),
                (
                    "academic_year",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.academicyear",
                        verbose_name="العام الدراسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات سعة لجان الكنترول",
                "verbose_name_plural": "إعدادات سعة لجان الكنترول",
            },
        ),
        migrations.CreateModel(
            name="StudentTermControlNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("term1", "الترم الأول"),
                            ("term2", "الترم الثاني"),
                            ("second_session", "الدور الثاني (ملاحق)"),
                        ],
                        max_length=20,
                        verbose_name="الترم / الفترة",
                    ),
                ),
                (
                    "seating_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=4,
                        null=True,
                        verbose_name="رقم الجلوس",
                    ),
                ),
                (
                    "secret_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=6,
                        null=True,
                        verbose_name="الرقم السري",
                    ),
                ),
                (
                    "committee_number",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="لجنة رقم"
                    ),
                ),
                (
                    "seat_number_in_committee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="رقم المقعد داخل اللجنة"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.academicyear",
                        verbose_name="العام الدراسي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_numbers",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "رقم جلوس وسري ولجنة للطالب",
                "verbose_name_plural": "شيت أرقام الجلوس واللجان الشامل",
                "unique_together": {("student", "academic_year", "term")},
            },
        ),
    ]
