# Generated by Django 6.0.3 on 2026-03-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_inventoryrestock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['id'], 'verbose_name': 'صنف مخزني (جرد)', 'verbose_name_plural': 'المخزن (الجرد التفصيلي)'},
        ),
    ]
