# Generated by Django 5.1.5 on 2026-07-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_student_study_type_controlroomconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="specialization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("General", "شعبة عامة"),
                    ("Restaurant", "فني مضيف"),
                    ("Kitchen", "فن طاهي"),
                    ("Internal", " مشرف غرف"),
                    ("Kitchen", " مطبخ"),
                    ("Restaurant", "مطعم"),
                    ("Tourism Services", "خدمات سياحية"),
                ],
                db_index=True,
                max_length=30,
                null=True,
                verbose_name="التخصص",
            ),
        ),
    ]
