# Generated by Django 6.0.3 on 2026-03-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_inventoryitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الرصيد الافتتاحي'),
        ),
    ]
