# Generated by Django 5.1.5 on 2026-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_alter_student_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="specialization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("General", "شعبة عامة"),
                    ("Host", "فني مضيف"),
                    ("Chef", "فن طاهي"),
                    ("Internal", "مشرف غرف"),
                    ("Kitchen", "مطبخ"),
                    ("Restaurant", "مطعم"),
                    ("Tourism_Services", "خدمات سياحية"),
                ],
                db_index=True,
                max_length=30,
                null=True,
                verbose_name="التخصص",
            ),
        ),
    ]
