# Generated by Django 6.0.3 on 2026-03-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_inventoryitem_stock_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('item_type', 'subject', 'uniform', 'grade')},
        ),
    ]
