# Generated by Django 5.1.5 on 2026-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_alter_student_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_notes",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ملاحظات حالة القيد"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "مستجد"),
                    ("Promoted", "منقول"),
                    ("Retained", "باق"),
                    ("Transferred", "محول"),
                    ("Dismissed", "مفصول"),
                    ("First_Round", "دور أول"),
                    ("Second_Round", "دور ثان"),
                ],
                max_length=20,
                null=True,
                verbose_name="حالة القيد",
            ),
        ),
    ]
