# Generated by Django 5.1.5 on 2026-07-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_student_enrollment_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "مستجد"),
                    ("Promoted", "منقول"),
                    ("Retained", "باق"),
                    ("Transferred", "محول"),
                    ("Dismissed", "مفصول"),
                    ("First_Round", "دور أول"),
                    ("Second_Round", "دور ثان"),
                    ("Graduated", "إتمام مرحلة"),
                ],
                max_length=20,
                null=True,
                verbose_name="حالة القيد",
            ),
        ),
    ]
