# Generated by Django 5.1.5 on 2026-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_alter_student_enrollment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="application_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="رسوم فتح الملف المسجلة",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="initial_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "مستجد"),
                    ("Promoted", "منقول"),
                    ("Retained", "باق"),
                    ("Transferred", "محول"),
                    ("Dismissed", "مفصول"),
                    ("First_Round", "دور أول"),
                    ("Second_Round", "دور ثان"),
                    ("Graduated", "إتمام مرحلة"),
                ],
                default="New",
                max_length=20,
                null=True,
                verbose_name="حالة القيد عند فتح الملف",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="is_application_fee_exempt",
            field=models.BooleanField(
                default=False, verbose_name="معافى من رسوم فتح الملف"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "مستجد"),
                    ("Promoted", "منقول"),
                    ("Retained", "باق"),
                    ("Transferred", "محول"),
                    ("Dismissed", "مفصول"),
                    ("First_Round", "دور أول"),
                    ("Second_Round", "دور ثان"),
                    ("Graduated", "إتمام مرحلة"),
                ],
                default="New",
                max_length=20,
                null=True,
                verbose_name="حالة الطالب الحالية",
            ),
        ),
    ]
