# Generated by Django 5.1.5 on 2026-07-26 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_student_application_fee_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booksale",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التسليم الفعلي"
            ),
        ),
        migrations.AddField(
            model_name="booksale",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivered_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظف المسلم",
            ),
        ),
    ]
