# Generated by Django 5.1.5 on 2026-08-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0021_booksale_delivered_at_booksale_delivered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksale",
            name="is_delivered",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="تم الاستلام من المخزن؟"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="item_type",
            field=models.CharField(
                choices=[("book", "كتاب دراسي"), ("uniform", "زي مدرسي")],
                db_index=True,
                default="book",
                max_length=10,
                verbose_name="نوع الصنف",
            ),
        ),
    ]
