# Generated by Django 5.1.5 on 2026-08-03 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0022_alter_booksale_is_delivered_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الدكتور")),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="التخصص"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="subjectprice",
            options={
                "verbose_name": "تعريفة سعر كورس / مجموعة",
                "verbose_name_plural": "أسعار المجموعات والاشتراكات (ربط السعر الكورس)",
            },
        ),
        migrations.AlterField(
            model_name="subjectprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="سعر الكورس / الباقة"
            ),
        ),
        migrations.AlterField(
            model_name="subjectprice",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("group", "مجموعة (Group)"),
                    ("individual", "كورس (فردي)"),
                    ("online", "أونلاين (Online)"),
                    ("revision", "مراجعة نهائية"),
                    ("vip", "خاص (VIP)"),
                ],
                default="group",
                max_length=20,
                verbose_name="نوع الكورس / التدريس",
            ),
        ),
        migrations.CreateModel(
            name="AcademyCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="اسم الكورس / الدبلومة"
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        default=14, verbose_name="مدة الدراسة بالشهور"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="السعر الموحد للكورس",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academydoctor",
                        verbose_name="الدكتور المحاضر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademyEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر مخصص للطالب (اختياري)",
                    ),
                ),
                (
                    "is_graduated",
                    models.BooleanField(default=False, verbose_name="تم منحه الشهادة؟"),
                ),
                (
                    "certificate_issued_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ إصدار الشهادة"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academycourse",
                        verbose_name="الكورس الأكاديمي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademyLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المحاضرة"),
                ),
                (
                    "lecture_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المحاضرة"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="students.academycourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "حاضر"), ("absent", "غائب")],
                        default="present",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="students.academyenrollment",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academylecture",
                    ),
                ),
            ],
        ),
    ]
