# Generated by Django 5.1.5 on 2026-08-03 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0023_academydoctor_alter_subjectprice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academyattendance",
            options={
                "verbose_name": "حضور محاضرة",
                "verbose_name_plural": "سجل حضور المحاضرات الأكاديمية",
            },
        ),
        migrations.AlterModelOptions(
            name="academycourse",
            options={
                "verbose_name": "كورس أكاديمي",
                "verbose_name_plural": "الكورسات الأكاديمية",
            },
        ),
        migrations.AlterModelOptions(
            name="academydoctor",
            options={
                "verbose_name": "دكتور / محاضر أكاديمي",
                "verbose_name_plural": "الدكاترة والمحاضرون",
            },
        ),
        migrations.AlterModelOptions(
            name="academyenrollment",
            options={
                "verbose_name": "اشتراك أكاديمي",
                "verbose_name_plural": "اشتراكات الأكاديمية",
            },
        ),
        migrations.AlterModelOptions(
            name="academylecture",
            options={
                "verbose_name": "محاضرة أكاديمية",
                "verbose_name_plural": "المحاضرات الأكاديمية",
            },
        ),
        migrations.AlterField(
            model_name="academyattendance",
            name="status",
            field=models.CharField(
                choices=[("present", "حاضر"), ("absent", "غائب")],
                db_index=True,
                default="present",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="academycourse",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="اسم الكورس / الدبلومة"
            ),
        ),
        migrations.AlterField(
            model_name="academydoctor",
            name="name",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="اسم الدكتور"
            ),
        ),
        migrations.AlterField(
            model_name="academyenrollment",
            name="enrollment_date",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ التسجيل",
            ),
        ),
        migrations.AlterField(
            model_name="academyenrollment",
            name="is_graduated",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="تم منحه الشهادة؟"
            ),
        ),
        migrations.AlterField(
            model_name="academylecture",
            name="lecture_date",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ المحاضرة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academyattendance",
            unique_together={("enrollment", "lecture")},
        ),
        migrations.AddIndex(
            model_name="academyenrollment",
            index=models.Index(
                fields=["student", "course"], name="students_ac_student_ca64f2_idx"
            ),
        ),
    ]
