# Generated by Django 5.1.5 on 2026-08-04 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_alter_academyattendance_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademySubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="اسم المادة الأكاديمية",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="كود المادة"
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة أكاديمية",
                "verbose_name_plural": "3. دليل المواد الأكاديمية",
            },
        ),
        migrations.CreateModel(
            name="AcademyTermSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "التيرم الأول (الشهور 1-3)"),
                            (2, "التيرم الثاني (الشهور 4-6)"),
                            (3, "التيرم الثالث (الشهور 7-9)"),
                            (4, "التيرم الرابع (الشهور 10-12)"),
                            (5, "التدريب العملي والامتياز (الشهور 13-14)"),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name="التيرم / الفصل الدراسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسكين مادة ودكتور بالتيرم",
                "verbose_name_plural": "4. الخطة الدراسية وتسكين المواد والدكاترة",
            },
        ),
        migrations.AlterModelOptions(
            name="academyattendance",
            options={
                "verbose_name": "حضور محاضرة",
                "verbose_name_plural": "7. سجل حضور المحاضرات",
            },
        ),
        migrations.AlterModelOptions(
            name="academycourse",
            options={
                "verbose_name": "قسم / دبلومة أكاديمية",
                "verbose_name_plural": "2. الأقسام والدبلومات",
            },
        ),
        migrations.AlterModelOptions(
            name="academydoctor",
            options={
                "verbose_name": "دكتور / محاضر أكاديمي",
                "verbose_name_plural": "1. الدكاترة والمحاضرون",
            },
        ),
        migrations.AlterModelOptions(
            name="academyenrollment",
            options={
                "verbose_name": "اشتراك طالب بأكاديمية",
                "verbose_name_plural": "5. اشتراكات الطلاب بالأكاديمية",
            },
        ),
        migrations.AlterModelOptions(
            name="academylecture",
            options={
                "verbose_name": "محاضرة أكاديمية",
                "verbose_name_plural": "6. محاضرات التيرمات",
            },
        ),
        migrations.RemoveField(
            model_name="academycourse",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="academylecture",
            name="course",
        ),
        migrations.AddField(
            model_name="academycourse",
            name="total_terms",
            field=models.PositiveIntegerField(
                default=4, verbose_name="عدد التيرمات / الفصول الدراسية"
            ),
        ),
        migrations.AlterField(
            model_name="academyattendance",
            name="status",
            field=models.CharField(
                choices=[("present", "حاضر"), ("absent", "غائب")],
                db_index=True,
                default="present",
                max_length=10,
                verbose_name="حالة الحضور",
            ),
        ),
        migrations.AlterField(
            model_name="academycourse",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="السعر الموحد للدبلومة"
            ),
        ),
        migrations.AlterField(
            model_name="academycourse",
            name="duration_months",
            field=models.PositiveIntegerField(
                default=14, verbose_name="مدة الدراسة الشاملة بالشهور"
            ),
        ),
        migrations.AlterField(
            model_name="academycourse",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="اسم القسم / الدبلومة"
            ),
        ),
        migrations.AlterField(
            model_name="academydoctor",
            name="name",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="اسم الدكتور / المحاضر"
            ),
        ),
        migrations.AlterField(
            model_name="academydoctor",
            name="specialty",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="التخصص الأكاديمي"
            ),
        ),
        migrations.AlterField(
            model_name="academyenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.academycourse",
                verbose_name="القسم / الدبلومة",
            ),
        ),
        migrations.AlterField(
            model_name="academyenrollment",
            name="enrollment_date",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ بدء الدراسة",
            ),
        ),
        migrations.AlterField(
            model_name="academyenrollment",
            name="is_graduated",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="تم منحه الشهادة الرسمية؟"
            ),
        ),
        migrations.AlterField(
            model_name="academyenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
                verbose_name="الطالب المتدرب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academyenrollment",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="academyattendance",
            index=models.Index(
                fields=["enrollment", "status"], name="students_ac_enrollm_6c9d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academyenrollment",
            index=models.Index(
                fields=["enrollment_date", "is_graduated"],
                name="students_ac_enrollm_7968d4_idx",
            ),
        ),
        migrations.AddField(
            model_name="academytermsubject",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="term_subjects",
                to="students.academycourse",
                verbose_name="القسم / الدبلومة",
            ),
        ),
        migrations.AddField(
            model_name="academytermsubject",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.academydoctor",
                verbose_name="الدكتور المحاضر للمادة",
            ),
        ),
        migrations.AddField(
            model_name="academytermsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.academysubject",
                verbose_name="المادة الدراسية",
            ),
        ),
        migrations.AddField(
            model_name="academylecture",
            name="term_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="students.academytermsubject",
                verbose_name="المادة والمحاضر بالتيرم",
            ),
        ),
        migrations.AddIndex(
            model_name="academytermsubject",
            index=models.Index(
                fields=["course", "term_number"], name="students_ac_course__e57a6d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academytermsubject",
            unique_together={("course", "term_number", "subject", "doctor")},
        ),
    ]
