# Generated by Django 5.1.5 on 2026-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0025_academysubject_academytermsubject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAdmissionNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name_ar",
                    models.CharField(max_length=250, verbose_name="اسم الطالب"),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="الرقم القومي"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم التليفون")),
                (
                    "whatsapp_number",
                    models.CharField(max_length=20, verbose_name="رقم الواتساب"),
                ),
                ("gender", models.CharField(max_length=10, verbose_name="النوع")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "birth_governorate",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المحافظة"
                    ),
                ),
                ("address", models.TextField(verbose_name="العنوان")),
                (
                    "current_qualification",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="المؤهل"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="تم تسجيله رسمياً"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "إشعار طلب التحاق",
                "verbose_name_plural": "إشعارات طلبات الالتحاق المعتمدة",
                "ordering": ["-received_at"],
            },
        ),
    ]
