# Generated by Django 5.1.5 on 2026-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0026_pendingadmissionnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingadmissionnotification",
            name="birth_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pending_docs/",
                verbose_name="شهادة الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="pendingadmissionnotification",
            name="parent_id_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pending_docs/",
                verbose_name="بطاقة ولي الأمر",
            ),
        ),
        migrations.AddField(
            model_name="pendingadmissionnotification",
            name="qualification_photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pending_docs/",
                verbose_name="بيان النجاح",
            ),
        ),
        migrations.AddField(
            model_name="pendingadmissionnotification",
            name="student_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pending_students/",
                verbose_name="صورة الطالب",
            ),
        ),
    ]
