# Generated by Django 5.1.5 on 2026-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0027_pendingadmissionnotification_birth_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="الرقم القومي / جواز السفر",
            ),
        ),
    ]
