# Generated by Django 5.1.5 on 2026-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0028_alter_student_national_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="تاريخ الرصد"
            ),
        ),
    ]
