# Generated by Django 5.1.5 on 2026-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0029_examresult_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="search_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="الاسم للبحث السريع",
            ),
        ),
    ]
