# Generated by Django 5.1.5 on 2026-09-08 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0003_alter_itemmaster_sku"),
        ("students", "0030_student_search_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSaleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("book", "كتب دراسية"), ("uniform", "زي مدرسي")],
                        max_length=20,
                        verbose_name="نوع الصرف",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي المطلوب (ج.م)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي المدفوع (ج.م)",
                    ),
                ),
                (
                    "is_fully_delivered",
                    models.BooleanField(
                        default=False, verbose_name="تم التسليم بالكامل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ ووقت العملية"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن تسليم طالب",
                "verbose_name_plural": "2. أذونات تسليم الطلاب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleDeliveryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="تم التسليم"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التسليم الفعلي"
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُسلم العهدة",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_inventory.itemmaster",
                        verbose_name="الصنف (الكتاب/الزي)",
                    ),
                ),
                (
                    "sale_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_details",
                        to="students.studentsalerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفصيلة تسليم",
                "verbose_name_plural": "3. تفاصيل التسليمات (Checklist)",
            },
        ),
        migrations.CreateModel(
            name="GradeItemPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[("book", "كتب دراسية"), ("uniform", "زي مدرسي")],
                        max_length=20,
                        verbose_name="نوع الباقة",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="سعر الباقة الإجمالي (ج.م)",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.grade",
                        verbose_name="الصف الدراسي",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        to="core_inventory.itemmaster",
                        verbose_name="الأصناف المقررة من المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "باقة مقررات صف",
                "verbose_name_plural": "1. باقات المقررات والزي (Packages)",
                "unique_together": {("grade", "package_type")},
            },
        ),
    ]
