# Generated by Django 5.1.5 on 2026-09-21 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0031_studentsalerecord_saledeliverydetail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القسم"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف القسم"),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظف المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="students.department",
                verbose_name="القسم",
            ),
        ),
    ]
