# Generated by Django 5.1.5 on 2026-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0033_alter_teacher_employee_alter_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miscellaneousrevenue",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ ووقت الإيراد"
            ),
        ),
        migrations.AlterField(
            model_name="miscellaneousrevenue",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="بيان الإيراد"
            ),
        ),
    ]
