# Generated by Django 5.1.5 on 2026-09-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0034_alter_miscellaneousrevenue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miscellaneousrevenue",
            name="revenue_type",
            field=models.CharField(
                choices=[
                    ("canteen", "إيجار كانتين"),
                    ("sports", "أنشطة رياضية"),
                    ("activities", "رسوم أنشطة / رحلات"),
                    ("papers", "رسوم استخراج أوراق"),
                    ("other", "أخرى متنوعة"),
                ],
                default="other",
                max_length=50,
                verbose_name="تصنيف الإيراد",
            ),
        ),
    ]
