# Generated by Django 6.0.3 on 2026-03-28 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GradePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر المحدد لهذا الصف')),
            ],
            options={
                'verbose_name': 'قائمة أسعار الصفوف',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة الدراسية')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي مبلغ الخطة')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='عدد الأقساط')),
                ('interest_value', models.DecimalField(decimal_places=2, default=0, help_text='قيمة فائدة ثابتة تضاف لإجمالي الخطة', max_digits=10, verbose_name='قيمة الفائدة الإضافية')),
            ],
            options={
                'verbose_name': 'خطة مصروفات',
                'verbose_name_plural': 'خطط المصروفات',
            },
        ),
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='الكمية المتاحة في المخزن')),
            ],
            options={
                'verbose_name': 'تعريف مخزن (صنف)',
                'verbose_name_plural': 'المخزن العام (الأصناف)',
            },
        ),
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف (مثل: كتاب لغة عربية)')),
            ],
            options={
                'verbose_name': 'تعريف صنف',
                'verbose_name_plural': 'تعريفات الأصناف',
            },
        ),
        migrations.CreateModel(
            name='MonthlyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تم تقفيل الخزينة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب القسط')),
            ],
            options={
                'verbose_name': 'بند خطة',
                'verbose_name_plural': 'بنود الخطط',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
            ],
            options={
                'verbose_name': 'فئة إيراد',
                'verbose_name_plural': 'فئات الإيرادات',
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المصروفات')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حساب طالب مالي',
                'verbose_name_plural': 'حسابات الطلاب المالية',
            },
        ),
        migrations.CreateModel(
            name='StudentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة القسط الأصلية')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع فعلياً')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='غرامة تأخير')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Partial', 'دفع جزئي'), ('Paid', 'تم الدفع'), ('Late', 'متأخر')], default='Pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قسط طالب',
                'verbose_name_plural': 'أقساط الطلاب',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_date', models.DateTimeField(auto_now_add=True)),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ النظري')),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الفعلي')),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الفارق')),
                ('closure_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الجرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات وتفاصيل الفئات')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إغلاق الخزينة اليومي',
                'verbose_name_plural': 'إغلاقات الخزينة اليومية',
                'ordering': ['-closure_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التسليم')),
                ('is_received', models.BooleanField(default=True, verbose_name='تم الاستلام فعلياً')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول عن التسليم')),
            ],
            options={
                'verbose_name': 'سجل تسليم طالب',
                'verbose_name_plural': 'سجلات استلام الطلاب',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
