# Generated by Django 6.0.3 on 2026-03-28 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='gradepricelist',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AddField(
            model_name='gradepricelist',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='finance.inventorymaster', verbose_name='الصنف'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.itemdefinition', verbose_name='الصنف'),
        ),
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='payment',
            name='closure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.dailyclosure', verbose_name='رقم الجرد/الإغلاق'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL, verbose_name='المحصل (الموظف)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='planitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.installmentplan'),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.revenuecategory', verbose_name='الفئة الرئيسية'),
        ),
        migrations.AddField(
            model_name='payment',
            name='revenue_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.revenuecategory', verbose_name='فئة الإيراد'),
        ),
        migrations.AddField(
            model_name='gradepricelist',
            name='revenue_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.revenuecategory', verbose_name='الفئة/الصنف'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='installment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.installmentplan'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='revenue_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.revenuecategory', verbose_name='بند الإيراد المرتبط'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentinstallment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='studentinstallment',
            name='installment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.installmentplan'),
        ),
        migrations.AddField(
            model_name='studentinstallment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً للإيرادات الحرة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentinstallment'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryrecord',
            unique_together={('student', 'inventory_item')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorymaster',
            unique_together={('item', 'grade', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='gradepricelist',
            unique_together={('revenue_category', 'grade', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentaccount',
            unique_together={('student', 'academic_year', 'revenue_category')},
        ),
        migrations.AddConstraint(
            model_name='studentinstallment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'installment_number'), name='unique_student_installment_per_year'),
        ),
    ]
