# Generated by Django 6.0.2 on 2026-02-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='students.student'),
        ),
        migrations.AddField(
            model_name='installment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.studentaccount'),
        ),
        migrations.AddField(
            model_name='studentinstallment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='studentinstallment',
            name='installment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.installmentplan'),
        ),
        migrations.AddField(
            model_name='studentinstallment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentinstallment'),
        ),
        migrations.AddConstraint(
            model_name='studentinstallment',
            constraint=models.UniqueConstraint(fields=('student', 'installment_number'), name='unique_student_installment'),
        ),
    ]
