# Generated by Django 6.0.2 on 2026-03-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryrecord',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'سجل تسليم طالب', 'verbose_name_plural': 'سجلات استلام الطلاب'},
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='is_received',
            field=models.BooleanField(default=True, verbose_name='تم الاستلام فعلياً'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات التسليم'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول عن التسليم'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='finance.inventorymaster', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب'),
        ),
    ]
