# Generated by Django 6.0.3 on 2026-04-06 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=50, verbose_name='رقم الدفتر')),
                ('start_serial', models.PositiveIntegerField(verbose_name='بداية السيريال')),
                ('end_serial', models.PositiveIntegerField(verbose_name='نهاية السيريال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الإيصال الورقي المرجعي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (المحصل)')),
            ],
            options={
                'verbose_name': 'دفتر إيصالات',
                'verbose_name_plural': 'دفاتر الإيصالات',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'is_active'), name='unique_active_book_per_user')],
            },
        ),
    ]
