# Generated by Django 6.0.3 on 2026-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='رقم الإيصال المرجعي'),
        ),
    ]
