# Generated by Django 6.0.2 on 2026-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='account',
        ),
        migrations.RemoveConstraint(
            model_name='studentinstallment',
            name='unique_student_installment',
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='number_of_installments',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='studentinstallment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'installment_number'), name='unique_student_installment_per_year'),
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
