# Generated by Django 6.0.3 on 2026-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_receiptbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الإيصال الورقي المرجعي'),
        ),
    ]
