# Generated by Django 6.0.2 on 2026-03-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_deliveryrecord_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymaster',
            name='price',
        ),
        migrations.CreateModel(
            name='GradePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر المحدد لهذا الصف')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='العام الدراسي')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='الصف الدراسي')),
                ('revenue_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.revenuecategory', verbose_name='الفئة/الصنف')),
            ],
            options={
                'verbose_name': 'قائمة أسعار الصفوف',
                'unique_together': {('revenue_category', 'grade', 'academic_year')},
            },
        ),
    ]
