# Generated by Django 6.0.3 on 2026-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='administrative_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='قيمة ثابتة تُحدد من الإدارة. لا تدخل ضمن أقساط الطالب أو مديونيته، وتُطالب بها الخزينة كإيراد منفصل.', max_digits=10, verbose_name='رسوم إدارية (إيراد حر منفصل)'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='interest_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='قيمة فائدة ثابتة تضاف لإجمالي الخطة وتُقسط على الطالب مع البنود', max_digits=10, verbose_name='قيمة الفائدة الإضافية'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي مبلغ الخطة (يُقسط)'),
        ),
    ]
