# Generated by Django 6.0.3 on 2026-04-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الإيصال الورقي المرجعي'),
        ),
    ]
