# Generated by Django 6.0.3 on 2026-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_installmentplan_administrative_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='administrative_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='قيمة ثابتة تُحدد من الإدارة. لا تدخل ضمن أقساط الطالب أو مديونيته، وتُطالب بها الخزينة كإيراد منفصل.', max_digits=10, verbose_name='رسوم إدارية (غرامه تاخير)'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='interest_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تحصل مباشره من الخزينه', max_digits=10, verbose_name='رسوم فتح الملف'),
        ),
    ]
