# Generated by Django 6.0.3 on 2026-03-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_inventorymaster_price_gradepricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='revenue_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.revenuecategory', verbose_name='بند الإيراد المرتبط'),
        ),
    ]
