# Generated by Django 6.0.3 on 2026-04-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_installmentplan_administrative_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم بند المصروف (مثل: كهرباء، بوفيه، إلخ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط متاح للاستخدام')),
            ],
            options={
                'verbose_name': 'بند مصروف (قائمة)',
                'verbose_name_plural': 'قائمة بنود المصروفات',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='أو اكتب بيان الصرف يدوياً'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expenseitem', verbose_name='اختر البند (من القائمة)'),
        ),
    ]
