# Generated by Django 6.0.3 on 2026-04-06 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_expense_receipt_number_payment_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyclosure',
            options={'ordering': ['-closure_date'], 'verbose_name': 'إغلاق خزينة', 'verbose_name_plural': 'أرشيف الجرد اليومي'},
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الفعلي (العد)'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closure_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الجرد'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closure_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الجرد المرجعي'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الدفتري (النظام)'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الفارق (عجز/زيادة)'),
        ),
    ]
