# Generated by Django 6.0.3 on 2026-04-07 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_dailyclosure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyclosure',
            options={'ordering': ['-closure_date']},
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الفعلي'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الجرد'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closure_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الدفتري'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الفارق'),
        ),
    ]
