# Generated by Django 6.0.3 on 2026-03-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_studentaccount_student'),
        ('students', '0005_alter_student_national_id_alter_student_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='students.student'),
        ),
    ]
