# Generated by Django 6.0.3 on 2026-03-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_studentaccount_student'),
        ('students', '0005_alter_student_national_id_alter_student_student_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentaccount',
            unique_together={('student', 'academic_year')},
        ),
    ]
