# Generated by Django 5.1.5 on 2026-06-13 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payment_cancellation_reason_payment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم ضمه للجرد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم تقفيل الخزينة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الدفع'),
        ),
    ]
