# Generated by Django 6.0.3 on 2026-04-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_dailyclosure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyclosure',
            options={'ordering': ['-closure_date'], 'verbose_name': 'إغلاق الخزينة اليومي', 'verbose_name_plural': 'إغلاقات الخزينة اليومية'},
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closure_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='closure_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الجرد'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات وتفاصيل الفئات'),
        ),
        migrations.AlterField(
            model_name='dailyclosure',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ النظري'),
        ),
    ]
