# Generated by Django 5.1.5 on 2026-06-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_expense_date_alter_expense_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'عملية الدفع', 'verbose_name_plural': 'عمليات الدفع'},
        ),
    ]
