# Generated by Django 6.0.3 on 2026-03-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_studentaccount_unique_together'),
        ('students', '0005_alter_student_national_id_alter_student_student_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentaccount',
            unique_together={('student', 'academic_year', 'revenue_category')},
        ),
    ]
