# Generated by Django 6.0.3 on 2026-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_dailyclosure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الإيصال المرجعي'),
        ),
    ]
