# Generated by Django 6.0.3 on 2026-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('petty', 'مصروفات نثرية'), ('general', 'مصروفات عمومية')], default='petty', max_length=20, verbose_name='نوع المصروف'),
        ),
    ]
