# Generated by Django 5.1.5 on 2026-06-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'عملية الدفع', 'verbose_name_plural': 'عمليات دفع'},
        ),
    ]
