# Generated by Django 5.1.5 on 2026-06-20 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_payment_options'),
        ('students', '0009_alter_miscellaneousrevenue_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المسترد')),
                ('refund_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الاسترداد')),
                ('reason', models.TextField(default='سحب ملف', verbose_name='سبب الاسترداد (مثال: سحب ملف، نقل، إلخ)')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='تم تقفيل الخزينة')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.academicyear', verbose_name='السنة الدراسية')),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_refunds', to='finance.dailyclosure', verbose_name='رقم الجرد')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول المالي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إذن استرداد نقدي',
                'verbose_name_plural': 'مرتجعات الطلاب (الاستردادات)',
                'ordering': ['-refund_date', '-id'],
            },
        ),
    ]
