# Generated by Django 6.0.3 on 2026-04-12 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_expense_spent_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyclosure',
            name='total_collected',
        ),
        migrations.RemoveField(
            model_name='monthlyclosure',
            name='total_remaining',
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد المرحل للشهر التالي'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي الربح/الخسارة'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد أول المدة'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='total_revenues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات'),
        ),
        migrations.AlterField(
            model_name='monthlyclosure',
            name='month',
            field=models.DateField(verbose_name='الشهر'),
        ),
    ]
