# Generated by Django 5.1.5 on 2026-06-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_studentrefund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrefund',
            options={'ordering': ['-refund_date', '-id'], 'verbose_name': 'إذن استرداد نقدي', 'verbose_name_plural': 'مرتجعات الطلاب'},
        ),
        migrations.AlterField(
            model_name='studentrefund',
            name='reason',
            field=models.TextField(default='سحب ملف', verbose_name='سبب الاسترداد (مثال: سحب ملف)'),
        ),
    ]
