# Generated by Django 5.1.5 on 2026-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_studentcallnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="application_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="اكتب هنا قيمة رسوم فتح الملف المقررة لهذه السنة لتطبق تلقائياً عند إضافة كل طالب جديد",
                max_digits=10,
                verbose_name="رسوم فتح الملف لهذا العام",
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="سنة نشطة"),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(max_length=20, verbose_name="اسم السنة الدراسية"),
        ),
    ]
