# Generated by Django 5.1.5 on 2026-09-06 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_academicyear_application_fee_and_more"),
        ("students", "0029_examresult_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiptbook",
            name="receipt_number",
        ),
        migrations.AddField(
            model_name="payment",
            name="is_settlement_only",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="إيصال تسوية فقط (لا يُسمع بالخزينة)",
            ),
        ),
        migrations.AddField(
            model_name="receiptbook",
            name="prefix",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="بادئة الدفتر (مثل: EXP أو ACT)",
            ),
        ),
        migrations.AddField(
            model_name="studentinstallment",
            name="is_locked",
            field=models.BooleanField(
                default=False, verbose_name="قسط مجمد (لا يمكن تعديله)"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="رقم الإيصال المرجعي (مع البادئة)",
            ),
        ),
        migrations.AlterField(
            model_name="studentinstallment",
            name="due_date",
            field=models.DateField(db_index=True, verbose_name="تاريخ الاستحقاق"),
        ),
        migrations.AlterField(
            model_name="studentinstallment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "قيد الانتظار"),
                    ("Partial", "دفع جزئي"),
                    ("Paid", "تم الدفع"),
                    ("Late", "متأخر"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date", "is_closed", "is_settlement_only"],
                name="finance_pay_payment_448013_idx",
            ),
        ),
    ]
