# Generated by Django 6.0.3 on 2026-04-16 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True, verbose_name='رقم البصمة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعاقد')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='أجر الساعة')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قيمة التأمينات الاجتماعية')),
                ('medical_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قيمة التأمين الطبي')),
                ('penalties', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الجزاءات')),
                ('loans', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='السلفيات')),
                ('annual_leave_balance', models.IntegerField(default=21, verbose_name='رصيد الإجازات السنوية')),
                ('casual_leave_balance', models.IntegerField(default=6, verbose_name='رصيد الإجازات العارضة')),
                ('weekly_day_off', models.CharField(choices=[('Sunday', 'الأحد'), ('Monday', 'الإثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس'), ('Friday', 'الجمعة'), ('Saturday', 'السبت')], default='Friday', max_length=20, verbose_name='يوم الإجازة الأسبوعية (Day Off)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'إجازة سنوية'), ('Casual', 'إجازة عارضة'), ('Sick', 'إجازة مرضية'), ('Unpaid', 'إجازة بدون أجر')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('days', models.IntegerField(verbose_name='عدد الأيام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات/السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'سجل الإجازات',
            },
        ),
        migrations.CreateModel(
            name='PayrollArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='شهر الاستحقاق')),
                ('year', models.IntegerField(verbose_name='سنة الاستحقاق')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الأساسي وقتها')),
                ('days_present', models.IntegerField(verbose_name='أيام الحضور')),
                ('lateness_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم التأخير')),
                ('leaves_taken', models.IntegerField(default=0, verbose_name='إجازات الشهر')),
                ('absent_days', models.IntegerField(verbose_name='الغياب الفعلي')),
                ('absence_deduction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='خصم الغياب')),
                ('penalties', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الجزاءات المخصومة')),
                ('loans', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السلف المخصومة')),
                ('insurances', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التأمينات المخصومة')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب المستحق')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الترحيل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل مرتب مرحل',
                'verbose_name_plural': 'أرشيف المرتبات',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
