# Generated by Django 6.0.3 on 2026-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True, verbose_name='رقم البصمة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعاقد')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='أجر الساعة')),
                ('annual_leave_balance', models.IntegerField(default=21, verbose_name='رصيد الإجازات السنوية')),
                ('casual_leave_balance', models.IntegerField(default=6, verbose_name='رصيد الإجازات العارضة')),
                ('weekly_day_off', models.CharField(choices=[('Sunday', 'الأحد'), ('Monday', 'الإثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس'), ('Friday', 'الجمعة'), ('Saturday', 'السبت')], default='Friday', max_length=20, verbose_name='يوم الإجازة الأسبوعية (Day Off)')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
    ]
