# Generated by Django 6.0.3 on 2026-04-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة (مثلاً: الدوام الصباحي)')),
                ('work_start_time', models.TimeField(verbose_name='موعد الحضور الرسمي')),
                ('work_end_time', models.TimeField(verbose_name='موعد الانصراف الرسمي')),
                ('grace_period', models.PositiveIntegerField(default=15, verbose_name='فترة السماح (بالدقائق)')),
                ('deduction_multiplier', models.FloatField(default=1.0, verbose_name='معامل الخصم (ساعة التأخير بـ X ساعة)')),
                ('overtime_multiplier', models.FloatField(default=1.5, verbose_name='معامل الإضافي (ساعة الإضافي بـ X ساعة)')),
                ('monday', models.BooleanField(default=True, verbose_name='الاثنين')),
                ('tuesday', models.BooleanField(default=True, verbose_name='الثلاثاء')),
                ('wednesday', models.BooleanField(default=True, verbose_name='الأربعاء')),
                ('thursday', models.BooleanField(default=True, verbose_name='الخميس')),
                ('friday', models.BooleanField(default=False, verbose_name='الجمعة')),
                ('saturday', models.BooleanField(default=False, verbose_name='السبت')),
                ('sunday', models.BooleanField(default=True, verbose_name='الأحد')),
            ],
            options={
                'verbose_name': 'قاعدة حضور',
                'verbose_name_plural': 'قواعد الحضور',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True, verbose_name='رقم البصمة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='على رأس العمل')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('annual_balance', models.FloatField(default=21)),
                ('casual_balance', models.FloatField(default=6)),
                ('attendance_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.attendancerule', verbose_name='نظام الحضور المطبق')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee'),
        ),
        migrations.CreateModel(
            name='FingerprintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, verbose_name='رقم البصمة')),
                ('timestamp', models.DateTimeField(verbose_name='وقت البصمة')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'سجل البصمة الخام',
                'unique_together': {('emp_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'سنوية'), ('casual', 'عارضة'), ('sick', 'مرضي'), ('unpaid', 'بدون أجر')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبولة'), ('rejected', 'مرفوضة')], default='pending', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'عطلة رسمية')], max_length=20)),
                ('late_minutes', models.IntegerField(default=0)),
                ('overtime_hours', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
