# Generated by Django 5.1.5 on 2026-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='absent_deduction_days',
            field=models.FloatField(default=1.0, verbose_name='خصم الغياب (اليوم بـ X يوم)'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='requires_fingerprint',
            field=models.BooleanField(default=True, verbose_name='هل الموظف ملزم بالبصمة؟ (للإدارة العليا مثلاً)'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='deduction_hours',
            field=models.FloatField(default=0.0, verbose_name='ساعات الخصم المستحقة'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='تمت المعالجة المالية'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم القاعدة (مثلاً: دوام صباحي، مرن، مؤقت)'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='late_minutes',
            field=models.IntegerField(default=0, verbose_name='دقائق التأخير'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='overtime_hours',
            field=models.FloatField(default=0, verbose_name='ساعات الإضافي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='annual_balance',
            field=models.FloatField(default=21, verbose_name='رصيد سنوي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='casual_balance',
            field=models.FloatField(default=6, verbose_name='رصيد عارضة'),
        ),
    ]
