# Generated by Django 6.0.3 on 2026-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='medical_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قيمة التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='جزاءات أو سلفيات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قيمة التأمينات الاجتماعية'),
        ),
    ]
