# Generated by Django 6.0.3 on 2026-03-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_medical_insurance_employee_penalties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='loans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='السلفيات'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الجزاءات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم'),
        ),
    ]
