# Generated by Django 5.1.5 on 2026-06-02 14:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendancerule_absent_deduction_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerule',
            options={'verbose_name': 'لائحة حضور وانصراف', 'verbose_name_plural': 'لوائح الحضور والانصراف'},
        ),
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'verbose_name': 'سجل حضور يومي معالج', 'verbose_name_plural': 'سجلات الحضور اليومية المعالجة'},
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='deduction_multiplier',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='overtime_multiplier',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='requires_fingerprint',
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_deduction_multiplier',
            field=models.FloatField(default=1.0, verbose_name='معامل خصم التأخير (ساعة التأخير بـ X ساعة)'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='max_late_allowed_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name='أقصى مدة تأخير مسموح بها قبل اعتباره غياب نصف يوم'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='overtime_multiplier_normal',
            field=models.FloatField(default=1.5, verbose_name='معامل الإضافي في الأيام العادية'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='overtime_multiplier_weekend',
            field=models.FloatField(default=2.0, verbose_name='معامل الإضافي في العطلات والإجازات'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='shift_type',
            field=models.CharField(choices=[('fixed', 'دوام ثابت بمواعيد صارمة'), ('flexible', 'دوام مرن (عدد ساعات مستهدفة يومياً)'), ('open', 'مفتوح (بدون قيود حضور وانصراف - للإدارة العليا)')], default='fixed', max_length=15, verbose_name='نوع الوردية/الدوام'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='target_work_hours',
            field=models.FloatField(default=8.0, verbose_name='عدد الساعات المستهدفة يومياً (للصنف المرن)'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='absence_deduction_days',
            field=models.FloatField(default=0.0, verbose_name='أيام الخصم المباشر (بسبب الغياب)'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='actual_work_hours',
            field=models.FloatField(default=0.0, verbose_name='ساعات العمل الفعلية المقضاة'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول عن الاعتماد المالي'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_balance',
            field=models.FloatField(default=30.0, verbose_name='رصيد الإجازات المرضية المتاحة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 17, 39, 39, 897185)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='السبب المذكور للطلب'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='absent_deduction_days',
            field=models.FloatField(default=1.0, verbose_name='جزاء الغياب بدون إذن (اليوم بـ X يوم من الراتب)'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='grace_period',
            field=models.PositiveIntegerField(default=15, verbose_name='فترة السماح بالدقائق (لا يحسب عليها تأخير)'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم قاعدة الدوام'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='موعد الانصراف الرسمي'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='موعد الحضور الرسمي'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الدخول الفعلي'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الخروج الفعلي'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(verbose_name='تاريخ اليوم'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='deduction_hours',
            field=models.FloatField(default=0.0, verbose_name='ساعات الخصم من الراتب (بسبب التأخير)'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_records', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='تم ترحيله للحسابات الختامية للراتب'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='overtime_hours',
            field=models.FloatField(default=0.0, verbose_name='ساعات الإضافي المستحقة'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر (دوام كامل)'), ('half_day_absent', 'غياب نصف يوم'), ('absent', 'غائب بدون إذن'), ('leave', 'إجازة معتمدة'), ('holiday', 'عطلة نهاية أسبوع / رسمية')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='annual_balance',
            field=models.FloatField(default=21.0, verbose_name='رصيد الإجازات السنوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.attendancerule', verbose_name='لائحة العمل المطبقة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي التعاقدي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='casual_balance',
            field=models.FloatField(default=7.0, verbose_name='رصيد الإجازات العارضة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم التابع له'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود البصمة الرقمي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='على رأس العمل حالياً'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الموظف بالكامل'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ نهاية الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'سنوية'), ('casual', 'عارضة'), ('sick', 'مرضية'), ('unpaid', 'بدون أجر')], max_length=10, verbose_name='نوع الإجازة المطلوبة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ بداية الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار والمراجعة'), ('approved', 'موافق عليها ومخصومة'), ('rejected', 'مرفوضة قطعيّاً')], default='pending', max_length=10, verbose_name='حالة الطلب الإدارية'),
        ),
    ]
