# Generated by Django 5.1.5 on 2026-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_attendancerule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='insurance_basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الأجر الأساسي التأميني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الاستقطاع التأميني (حصة الموظف)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم التأميني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_variable_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='البدلات التأمينية / الأجر المتغير'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_insured',
            field=models.BooleanField(default=False, verbose_name='خاضع للتأمينات الاجتماعية؟'),
        ),
    ]
