# Generated by Django 6.0.3 on 2026-03-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_department_employee_loans_alter_employee_penalties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='شهر الاستحقاق')),
                ('year', models.IntegerField(verbose_name='سنة الاستحقاق')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الأساسي وقتها')),
                ('days_present', models.IntegerField(verbose_name='أيام الحضور')),
                ('absent_days', models.IntegerField(verbose_name='أيام الغياب')),
                ('absence_deduction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='خصم الغياب')),
                ('penalties', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الجزاءات المخصومة')),
                ('loans', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السلف المخصومة')),
                ('insurances', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التأمينات المخصومة')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب المستحق')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الترحيل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل مرتب مرحل',
                'verbose_name_plural': 'أرشيف المرتبات',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
