# Generated by Django 5.1.5 on 2026-08-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_employee_insurance_basic_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "is_working",
                    models.BooleanField(default=True, verbose_name="يوم عمل؟"),
                ),
                (
                    "shift_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="بداية الوردية الاستثنائية"
                    ),
                ),
                (
                    "shift_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="نهاية الوردية الاستثنائية"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول وردية",
                "verbose_name_plural": "جداول الورديات",
                "unique_together": {("employee", "date")},
            },
        ),
    ]
