# Generated by Django 6.0.3 on 2026-03-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_payrollarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'إجازة سنوية'), ('Casual', 'إجازة عارضة'), ('Sick', 'إجازة مرضية'), ('Unpaid', 'إجازة بدون أجر')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('days', models.IntegerField(verbose_name='عدد الأيام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات/السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'سجل الإجازات',
            },
        ),
    ]
