# Generated by Django 5.1.5 on 2026-08-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_shiftroster"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendance",
            name="administrative_penalty_days",
            field=models.FloatField(
                default=0.0, verbose_name="أيام الجزاء الإداري الصارم"
            ),
        ),
        migrations.AlterField(
            model_name="dailyattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر (دوام كامل)"),
                    ("half_day_absent", "غياب نصف يوم"),
                    ("absent", "غائب بدون إذن"),
                    ("leave", "إجازة معتمدة"),
                    ("holiday", "عطلة نهاية أسبوع / رسمية"),
                    ("mission", "مأمورية رسمية"),
                ],
                default="absent",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ بداية المأمورية")),
                ("end_date", models.DateField(verbose_name="تاريخ نهاية المأمورية")),
                ("reason", models.TextField(verbose_name="وجهة وتفاصيل المأمورية")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب مأمورية",
                "verbose_name_plural": "طلبات المأموريات",
            },
        ),
        migrations.CreateModel(
            name="PermissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ الإذن")),
                ("reason", models.TextField(verbose_name="سبب الاستئذان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب إذن",
                "verbose_name_plural": "طلبات الأذونات",
            },
        ),
    ]
