# Generated by Django 6.0.3 on 2026-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollarchive',
            name='leaves_taken',
            field=models.IntegerField(default=0, verbose_name='إجازات الشهر'),
        ),
        migrations.AlterField(
            model_name='payrollarchive',
            name='absent_days',
            field=models.IntegerField(verbose_name='الغياب الفعلي'),
        ),
    ]
