# Generated by Django 5.1.5 on 2026-08-25 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_dailyattendance_administrative_penalty_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسوية"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("addition", "إضافة مالية (مكافأة / استثناء / حافز)"),
                            ("deduction", "استقطاع مالي (سلفة / عهدة / غرامة)"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ (ج.م)"
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب الاعتماد (التوجيهات)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="hr.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
        ),
    ]
