# Generated by Django 6.0.3 on 2026-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_payrollarchive_leaves_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollarchive',
            name='lateness_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم التأخير'),
        ),
    ]
