# Generated by Django 5.1.5 on 2026-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_financialadjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        verbose_name="اسم العطلة (مثل: عيد الفطر، إجازة استثنائية)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ بداية العطلة")),
                ("end_date", models.DateField(verbose_name="تاريخ نهاية العطلة")),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات إضافية"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
