# Generated by Django 5.1.5 on 2026-09-05 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_alter_dailyattendance_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hr_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤولي الـ HR المخصصين لهذا الموظف",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="annual_balance",
            field=models.FloatField(default=15.0, verbose_name="رصيد الاعتيادية"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="casual_balance",
            field=models.FloatField(default=6.0, verbose_name="رصيد الإجازات العارضة"),
        ),
    ]
