# Generated by Django 5.1.5 on 2026-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_employee_hr_managers_alter_employee_annual_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "سنوية"),
                    ("casual", "عارضة"),
                    ("sick", "مرضية"),
                    ("exceptional", "استثنائية (مدفوعة الأجر)"),
                ],
                max_length=20,
                verbose_name="نوع الإجازة المطلوبة",
            ),
        ),
    ]
