# Generated by Django 5.1.5 on 2026-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_alter_leaverequest_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ التعيين / المباشرة"
            ),
        ),
    ]
