# Generated by Django 5.1.5 on 2026-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employee_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionrequest",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="وقت الخروج (يجب أن يكون بعد 2 ظهراً)",
            ),
        ),
    ]
