# Generated by Django 4.2.16 on 2026-09-13 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0013_permissionrequest_departure_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PenaltyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ توقيع الجزاء",
                    ),
                ),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("lateness", "تكرار التأخير عن الحضور"),
                            ("unauthorized_exit", "الخروج بدون إذن (تحايل)"),
                            ("negligence", "إهمال في العمل"),
                            ("misconduct", "مخالفة سلوكية / أدبية"),
                            ("violation", "مخالفة للوائح الداخلية"),
                            ("other", "أخرى (يُذكر السبب بالتفصيل)"),
                        ],
                        max_length=30,
                        verbose_name="نوع الجزاء",
                    ),
                ),
                (
                    "deduction_days",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="عدد أيام الخصم (يحددها المدير حسب خطورة المخالفة)",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب الجزاء وتفاصيله")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المدير الموقّع للجزاء",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="hr.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزاء إداري",
                "verbose_name_plural": "الجزاءات الإدارية",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
