# Generated by Django 4.2.16 on 2026-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_penaltyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار والمراجعة"),
                    ("approved", "موافق عليها ومخصومة"),
                    ("rejected", "مرفوضة قطعيّاً"),
                ],
                default="pending",
                max_length=10,
                verbose_name="حالة الطلب الإداري",
            ),
        ),
    ]
