# Generated by Django 5.1.5 on 2026-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0015_alter_leaverequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="initial_annual_balance",
            field=models.FloatField(
                default=15.0, verbose_name="الرصيد السنوي الافتتاحي"
            ),
        ),
    ]
