# Generated by Django 5.1.5 on 2026-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0016_employee_initial_annual_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر (دوام كامل)"),
                    ("half_day_absent", "غياب نصف يوم"),
                    ("absent", "غائب بدون إذن"),
                    ("leave", "إجازة معتمدة"),
                    ("mission", "مأمورية رسمية"),
                    ("holiday", "عطلة رسمية / استثنائية"),
                ],
                default="absent",
                max_length=20,
            ),
        ),
    ]
