# Generated by Django 5.1.5 on 2026-09-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_alter_dailyattendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="initial_annual_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="رصيد الإجازات المبدئي",
            ),
        ),
    ]
