# Generated by Django 5.1.5 on 2026-09-30 09:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_alter_employee_initial_annual_balance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missionrequest",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "طلب مأمورية",
                "verbose_name_plural": "طلبات المأموريات",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2026, 1, 1),
                null=True,
                verbose_name="تاريخ التعيين / المباشرة",
            ),
        ),
        migrations.AlterField(
            model_name="missionrequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
    ]
