# Generated by Django 5.1.5 on 2026-09-30 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0019_alter_missionrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendance",
            name="is_manual_override",
            field=models.BooleanField(
                default=False, verbose_name="تعديل يدوي (جزاء تحايل / انصراف يدوي)"
            ),
        ),
        migrations.AlterField(
            model_name="penaltyrecord",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="تاريخ توقيع الجزاء",
            ),
        ),
    ]
