"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
# 1. تحميل المتغيرات من ملف .env فوراً
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# 3. إعدادات الأمان (تقرأ من ملف .env)
# تأكد أنك أنشأت ملف .env بجانب manage.py وضعت فيه القيم
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 4. المضيفون المسموح لهم (سيتم تحديثها من القيم في أسفل الملف)
# جلب النطاقات المسموحة من ملف .env (مثل: ALLOWED_HOSTS=192.168.1.10,example.com)
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost')
# ALLOWED_HOSTS = allowed_hosts_env.split(',')
ALLOWED_HOSTS = ['*']

# أضف هذا الجزء للسماح لروابط Cloudflare بالتعامل مع النماذج (Forms)
# السماح لروابط Cloudflare المتغيرة بالتعامل مع النماذج وتسجيل الدخول
CSRF_TRUSTED_ORIGINS = ["https://*.trycloudflare.com"]
# أو إذا أردت كتابة الـ IP الخاص بالسيرفر مباشرة (استبدل بالرقم الحقيقي):
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.x.x', 'yourdomain.com']
# --- استكمال باقي إعدادات Django (INSTALLED_APPS, MIDDLEWARE...) ---

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'corsheaders',
    'students',
    'finance.apps.FinanceConfig',
    'treasury.apps.TreasuryConfig',
    'hr',
    'accounts',
    'audit',
    'crispy_forms',
    'crispy_bootstrap5',
    'debug_toolbar',

]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",  # المسار العام
            BASE_DIR / "students/templates/students/books",  # لو عايز Django يشوف القوالب مباشرة هنا
        ],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.active_academic_year',
                'students.context_processors.admission_status',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'school_db',
        'USER': 'sameh_admin',
        'PASSWORD': 'pass_123', # نفس اللي كتبناه في ملف docker-compose
        'HOST': 'db',           # لازم كلمة db مش localhost
        'PORT': '5432',
    }
}

db_from_env = dj_database_url.config(conn_max_age=600)
if db_from_env:
    DATABASES['default'].update(db_from_env)
    
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# أضف هذا السطر ليتمكن Django من العثور على مجلد static الخاص بك
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# للإنتاج (عندما ترفع الموقع على سيرفر حقيقي)
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


# --- إعدادات Celery ---
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# --- إعدادات البريد الإلكتروني وتنبيهات النظام ---
ADMIN_EMAIL = 'admin@school.com'
DEFAULT_FROM_EMAIL = 'system@school.com'

# --- إعدادات نظام تسجيل الدخول (Login Settings) ---
# هذا الجزء حيوي لضمان عمل شاشة الدخول والروابط التي أنشأناها
LOGIN_URL = 'login'               # توجيه المستخدم لصفحة الدخول عند الحاجة
LOGIN_REDIRECT_URL = 'home'        # الصفحة التي تفتح فور نجاح الدخول (صفحة الأزرار)
LOGOUT_REDIRECT_URL = 'login'      # الصفحة التي يذهب إليها المستخدم بعد تسجيل الخروج

# --- إعدادات الجلسة (لضمان استقرار النظام ومنع الـ Loop) ---
SESSION_COOKIE_AGE = 3600          # تنتهي الجلسة تلقائياً بعد ساعة واحدة
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # تسجيل خروج تلقائي بمجرد إغلاق المتصفح
# إعدادات لضمان تحديث الجلسة ومنع اللوب
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# إعدادات إضافية لكسر اللوب
APPEND_SLASH = True  # يضمن أن الروابط تنتهي بـ / دائماً
REMOVE_SLASH = False

CORS_ALLOW_ALL_ORIGINS = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# كود تشغيل لوحة فحص الأداء (Debug Toolbar) مع الدوكر
if DEBUG:
    import socket
    try:
        # البحث عن IP الحاوية (Container) لضمان ظهور اللوحة
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
        INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]
    except Exception:
        INTERNAL_IPS = ["127.0.0.1"]

    # إعداد إضافي للتأكد من ظهور اللوحة في المتصفح
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: True,
    }

# إعدادات الأمان في حالة توقف وضع التطوير (Production)
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # CSRF_COOKIE_SECURE = True
    # SESSION_COOKIE_SECURE = True
    # SECURE_SSL_REDIRECT = True