"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$)+v5nnd@3b608!*#ny9$ik^!2iq)700ovet!me=u+k)6op7@t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'students',
    'finance.apps.FinanceConfig',
    'treasury.apps.TreasuryConfig',
    'hr',
    'accounts',
    'audit',
    'crispy_forms',
    'crispy_bootstrap5',

]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",  # المسار العام
            BASE_DIR / "students/templates/students/books",  # لو عايز Django يشوف القوالب مباشرة هنا
        ],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.active_academic_year',
                'students.context_processors.admission_status',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'school_system_db',
        'USER': 'postgres',
        'PASSWORD': 'admin123', 
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# أضف هذا السطر ليتمكن Django من العثور على مجلد static الخاص بك
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# للإنتاج (عندما ترفع الموقع على سيرفر حقيقي)
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

import os

# --- إعدادات Celery ---
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# --- إعدادات البريد الإلكتروني وتنبيهات النظام ---
ADMIN_EMAIL = 'admin@school.com'
DEFAULT_FROM_EMAIL = 'system@school.com'

# --- إعدادات نظام تسجيل الدخول (Login Settings) ---
# هذا الجزء حيوي لضمان عمل شاشة الدخول والروابط التي أنشأناها
LOGIN_URL = 'login'               # توجيه المستخدم لصفحة الدخول عند الحاجة
LOGIN_REDIRECT_URL = 'home'        # الصفحة التي تفتح فور نجاح الدخول (صفحة الأزرار)
LOGOUT_REDIRECT_URL = 'login'      # الصفحة التي يذهب إليها المستخدم بعد تسجيل الخروج

# --- إعدادات الجلسة (لضمان استقرار النظام ومنع الـ Loop) ---
SESSION_COOKIE_AGE = 3600          # تنتهي الجلسة تلقائياً بعد ساعة واحدة
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # تسجيل خروج تلقائي بمجرد إغلاق المتصفح
# إعدادات لضمان تحديث الجلسة ومنع اللوب
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# إعدادات إضافية لكسر اللوب
APPEND_SLASH = True  # يضمن أن الروابط تنتهي بـ / دائماً
REMOVE_SLASH = False

# تأكد أن ALLOWED_HOSTS في ملفك الأصلي تسمح بالدخول المحلي
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']