# Generated by Django 6.0.3 on 2026-04-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الحركة')),
                ('category', models.CharField(choices=[('fees', 'مصروفات دراسية'), ('books', 'كتب وباقات دراسية'), ('bus', 'اشتراك باص'), ('other', 'إيرادات متنوعة')], max_length=20, verbose_name='نوع الإيراد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المورد')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإيصال المرجعي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('is_closed', models.BooleanField(default=False, help_text='تحدد ما إذا كانت هذه الحركة قد تم ترحيلها في جرد يومي سابق', verbose_name='تم الإغلاق بالجرد')),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.dailyclosure', verbose_name='رقم الجرد/الإغلاق')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستلم')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حركة خزينة مجمعة',
                'verbose_name_plural': 'الخزينة العامة (دفتر اليومية)',
                'ordering': ['-date'],
            },
        ),
    ]
