# Generated by Django 6.0.3 on 2026-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='category',
            field=models.CharField(max_length=100, verbose_name='نوع الإيراد'),
        ),
    ]
