# Generated by Django 5.1.5 on 2026-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_alter_generalledger_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم المسلسل')),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('is_original', models.BooleanField(default=True, verbose_name='أصلي؟')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات المسح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
