# Generated by Django 5.1.5 on 2026-05-25 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_alter_product_options_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disabled_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تعطيل مؤقت حتى تاريخ'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط (الـ QR يعمل)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات المسح الإجمالية'),
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت المسح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان الـ IP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='treasury.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تاريخ المسح',
                'verbose_name_plural': 'تواريخ المسح للمنتجات',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
