# Generated by Django 5.1.5 on 2026-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_product_disabled_until_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='is_discount',
            field=models.BooleanField(db_index=True, default=False, verbose_name='هل الحركة عبارة عن خصم/كوبون؟'),
        ),
    ]
