# Generated by Django 5.1.5 on 2026-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_generalledger_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='تحدد ما إذا كانت هذه الحركة قد تم ترحيلها في جرد يومي سابق', verbose_name='تم الإغلاق بالجرد'),
        ),
    ]
