# Generated by Django 5.1.5 on 2026-09-08 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0015_remove_receiptbook_receipt_number_and_more"),
        ("students", "0030_student_search_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المستودع"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="الموقع/المبنى",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "مستودع",
                "verbose_name_plural": "1. المستودعات",
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم التصنيف")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core_inventory.itemcategory",
                        verbose_name="التصنيف الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصنيف مخزني",
                "verbose_name_plural": "2. شجرة الأصناف",
            },
        ),
        migrations.CreateModel(
            name="ItemMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="كود الصنف (SKU/Barcode)",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الصنف")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("saleable", "مخزون للبيع (كتب/زي)"),
                            ("consumable", "مخزون استهلاكي (مطبخ/نظافة)"),
                            ("asset", "أصول ثابتة (تخت/أجهزة)"),
                        ],
                        default="saleable",
                        max_length=20,
                        verbose_name="طبيعة الصنف",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("piece", "قطعة / عدد"),
                            ("kg", "كيلوجرام"),
                            ("gram", "جرام"),
                            ("liter", "لتر"),
                            ("pack", "عبوة / كرتونة"),
                        ],
                        default="piece",
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("none", "بدون تتبع خاص"),
                            ("batch", "تتبع برقم التشغيلة وصلاحية (للمطعم)"),
                            ("serial", "تتبع بالسيريال نمبر (للأصول والأجهزة)"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="نوع التتبع",
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="حد الطلب (الحد الأدنى)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_inventory.itemcategory",
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "linked_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.grade",
                        verbose_name="الصف (للكتب والزي)",
                    ),
                ),
                (
                    "linked_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.subject",
                        verbose_name="المادة الدراسية (للكتب)",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة صنف",
                "verbose_name_plural": "3. بطاقات الأصناف (دليل المواد)",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_code",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الحركة",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN_PURCHASE", "وارد مشتريات"),
                            ("IN_RETURN", "وارد مرتجع (من طالب أو قسم)"),
                            ("OUT_STUDENT", "منصرف لطالب (بيع/تسليم)"),
                            ("OUT_DEPT", "منصرف لقسم (تشغيل مطبخ/نظافة)"),
                            ("OUT_WASTE", "منصرف هالك / تالف"),
                            ("TRANSFER", "تحويل بين المستودعات"),
                            ("ADJUST", "تسوية جردية (عجز/زيادة)"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الكمية"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القسم المستلم (للمطعم/النظافة)",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="رقم التشغيلة / الباتش",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الصلاحية"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="السيريال نمبر (للأصول)",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الحركة"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أمين المخزن",
                    ),
                ),
                (
                    "finance_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.payment",
                        verbose_name="رقم الإيصال المالي",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_inventory.itemmaster",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                        verbose_name="صرف لطالب",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مخزنية",
                "verbose_name_plural": "4. الحركات المخزنية (وارد ومنصرف)",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد المتاح",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_inventory.itemmaster",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "رصيد حالي",
                "verbose_name_plural": "5. الأرصدة الحالية في المستودعات",
                "unique_together": {("item", "warehouse")},
            },
        ),
    ]
