# Generated by Django 5.1.5 on 2026-09-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="اسم الوحدة"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الرمز المرجعي",
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة قياس",
                "verbose_name_plural": "وحدات القياس",
            },
        ),
        migrations.CreateModel(
            name="ItemUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="معامل التحويل (يساوي كم؟)",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="core_inventory.itemmaster",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convert_from",
                        to="core_inventory.unitofmeasure",
                        verbose_name="من وحدة (وحدة الشراء)",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convert_to",
                        to="core_inventory.unitofmeasure",
                        verbose_name="إلى وحدة (وحدة الصرف/التشغيل)",
                    ),
                ),
            ],
            options={
                "verbose_name": "معامل تحويل",
                "verbose_name_plural": "معاملات تحويل الوحدات",
                "unique_together": {("item", "from_unit", "to_unit")},
            },
        ),
    ]
