# Generated by Django 5.1.5 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0002_unitofmeasure_itemunitconversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmaster",
            name="sku",
            field=models.CharField(
                blank=True,
                max_length=50,
                unique=True,
                verbose_name="كود الصنف (SKU/Barcode)",
            ),
        ),
    ]
