# Generated by Django 5.1.5 on 2026-09-09 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0003_alter_itemmaster_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="اسم المورد / الشركة",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الافتتاحي (دائن)",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "6. الموردين",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemunitconversion",
            options={
                "verbose_name": "معامل تحويل",
                "verbose_name_plural": "9. معاملات تحويل الوحدات",
            },
        ),
        migrations.AlterModelOptions(
            name="unitofmeasure",
            options={
                "verbose_name": "وحدة قياس",
                "verbose_name_plural": "8. وحدات القياس",
            },
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="اسم التصنيف"
            ),
        ),
        migrations.AlterField(
            model_name="itemmaster",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("saleable", "مخزون للبيع (كتب/زي)"),
                    ("consumable", "مخزون استهلاكي (مطبخ/نظافة)"),
                    ("asset", "أصول ثابتة (تخت/أجهزة)"),
                ],
                db_index=True,
                default="saleable",
                max_length=20,
                verbose_name="طبيعة الصنف",
            ),
        ),
        migrations.AlterField(
            model_name="itemmaster",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="اسم الصنف"
            ),
        ),
        migrations.AlterField(
            model_name="itemmaster",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                unique=True,
                verbose_name="كود الصنف (SKU/Barcode)",
            ),
        ),
        migrations.AlterField(
            model_name="itemunitconversion",
            name="conversion_rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="معامل التحويل"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="batch_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="رقم التشغيلة / الباتش",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الحركة",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="expiry_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="تاريخ الصلاحية"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("IN_OPENING", "رصيد افتتاحي"),
                    ("IN_PURCHASE", "وارد مشتريات"),
                    ("IN_RETURN", "وارد مرتجع (من طالب أو قسم)"),
                    ("OUT_STUDENT", "منصرف لطالب (بيع/تسليم)"),
                    ("OUT_DEPT", "منصرف لقسم (تشغيل مطبخ/نظافة)"),
                    ("OUT_WASTE", "منصرف هالك / تالف"),
                    ("TRANSFER", "تحويل بين المستودعات"),
                    ("ADJUST", "تسوية جردية (عجز/زيادة)"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="نوع الحركة",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="serial_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="السيريال نمبر (للأصول)",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_code",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="رقم الحركة",
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="اسم الوحدة"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="اسم المستودع"
            ),
        ),
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الفاتورة",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ الفاتورة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="إجمالي الفاتورة",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الصافي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة (لم تعتمد)"),
                            ("approved", "معتمدة (مرحلة للمخزن)"),
                            ("cancelled", "ملغاة"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="حالة الفاتورة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سجلت بواسطة",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_invoices",
                        to="core_inventory.warehouse",
                        verbose_name="المستودع المستلم",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core_inventory.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة مشتريات",
                "verbose_name_plural": "7. فواتير المشتريات",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="سعر الشراء للوحدة",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="إجمالي السطر"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core_inventory.purchaseinvoice",
                        verbose_name="الفاتورة",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_history",
                        to="core_inventory.itemmaster",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف بالفاتورة",
                "verbose_name_plural": "أصناف الفاتورة",
            },
        ),
    ]
