# Generated by Django 5.1.5 on 2026-09-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0004_supplier_alter_itemunitconversion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="core_inventory.supplier",
                verbose_name="المورد",
            ),
        ),
    ]
