# Generated by Django 5.1.5 on 2026-09-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0005_alter_purchaseinvoice_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmaster",
            name="tracking_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون تتبع خاص"),
                    ("batch", "تتبع برقم التشغيلة وصلاحية (ل للمطعم)"),
                    ("serial", "تتبع بالسيريال نمبر (للأصول والأجهزة)"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع التتبع",
            ),
        ),
        migrations.AlterField(
            model_name="itemmaster",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core_inventory.unitofmeasure",
                verbose_name="وحدة القياس",
            ),
        ),
    ]
