# Generated by Django 5.1.5 on 2026-09-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0006_alter_itemmaster_tracking_type_and_more"),
        ("students", "0031_studentsalerecord_saledeliverydetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoiceitem",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.grade",
                verbose_name="الصف الدراسي",
            ),
        ),
    ]
