# Generated by Django 5.1.5 on 2026-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_inventory", "0007_purchaseinvoiceitem_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="رقم الحركة",
            ),
        ),
    ]
